import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { z } from "zod";

import {
  agentRegisterTool,
  agentWhoamiTool,
  companionPauseLocalTool,
  companionResumeLocalTool,
  companionStatusLocalTool,
  companionStopLocalTool,
  broadcastChatTool,
  swarmStopStatusTool,
  swarmStopTool,
  swarmResumeTool,
  syncWithBaseBranchTool,
  taskCreateTool,
  taskListTool,
  taskLinkTool,
  taskSetStatusTool,
  taskAssignTool,
  taskMarkDoneTool,
  taskCancelTool,
  updateTeamDashboardTool,
  worktreeCreateTool,
  worktreeListTool,
  worktreeRemoveTool,
  // v0.2 tools
  scanSystemMcpsTool,
  authorizeMcpsForSwarmTool,
  getPolicyTool,
  fileReserveTool,
  fileReleaseTool,
  listFileLocksTool,
  announceTaskForBiddingTool,
  bidForTaskTool,
  pollSwarmEventsTool,
  createGithubPrTool,
  checkMainHealthTool,
  signalDependencyChangeTool,
  syncDependenciesTool,
  requestCrossAgentReviewTool,
  respondToReviewTool,
  listPendingReviewsTool,
  shareScreenshotTool,
  listScreenshotsTool,
  // v0.3 tools
  decomposeTaskTool,
  getDecompositionTool,
  startVotingTool,
  castVoteTool,
  listOpenVotingsTool,
  autoDeleteMergedBranchTool,
  cleanupAllMergedBranchesTool,
  logSwarmThoughtTool,
  getRecentThoughtsTool,
  patrolModeTool,
  reportCiAlertTool,
  getImmuneStatusTool,
  runLocalTestsTool,
  forecastFileTouchesTool,
  checkFileConflictsTool,
  requestPlatformCheckTool,
  respondToPlatformCheckTool,
  getPendingPlatformChecksTool,
  // v0.4 orchestrator tools
  saveBriefingTool,
  loadBriefingTool,
  updateSwarmPulseTool,
  getSwarmPulseTool,
  archiveFindingTool,
  searchKnowledgeTool,
  triggerUrgentPreemptionTool,
  getActiveUrgentTool,
  createSnapshotTool,
  triggerRollbackTool,
  requestCollectiveAdviceTool,
  provideAdviceTool,
  autoGenerateDocsTool,
  trackExpertiseTool,
  suggestAgentForTaskTool,
  predictConflictsTool,
  // v0.4.1 Enhanced features
  generateTaskDocsTool,
  listDocsTool,
  getDocTool,
  recordAgentEditTool,
  suggestAgentAdvancedTool,
  getTopExpertsTool,
  listAgentExpertiseTool,
  analyzeConflictHistoryTool,
  getConflictHotspotsTool,
  checkFileSafetyTool,
  recordConflictEventTool,
  // v0.4.2 Timeline
  generateTimelineTool,
  getTimelineVisualizationTool,
  // v0.5 Agent Health Monitor
  checkAgentHealthTool,
  getDeadAgentsTool,
  forceReassignTaskTool,
  getSwarmHealthSummaryTool,
  // v0.5 Session Recording
  startSessionRecordingTool,
  logSessionActionTool,
  stopSessionRecordingTool,
  listSessionRecordingsTool,
  replaySessionTool,
  // v0.5 Quality Gate
  runQualityGateTool,
  getQualityReportTool,
  setQualityThresholdTool,
  checkPrReadyTool,
  // v0.5 Cost Tracker
  logApiUsageTool,
  getAgentCostsTool,
  getProjectCostsTool,
  setBudgetLimitTool,
  checkBudgetRemainingTool,
  // v0.5 Context Compressor
  estimateContextSizeTool,
  compressBriefingTool,
  compressMultipleBriefingsTool,
  getCompressionStatsTool,
  // v0.5 Regression Detector
  saveBaselineTool,
  checkRegressionTool,
  listRegressionsTool,
  resolveRegressionTool,
  listBaselinesTool,
  // v0.6 Brainstorming
  startBrainstormTool,
  askBrainstormQuestionTool,
  answerBrainstormQuestionTool,
  proposeApproachesTool,
  presentDesignSectionTool,
  validateDesignSectionTool,
  saveDesignDocumentTool,
  getBrainstormSessionTool,
  listBrainstormSessionsTool,
  // v0.6 Writing Plans
  createImplementationPlanTool,
  addPlanTaskTool,
  getNextTaskTool,
  startPlanTaskTool,
  completeStepTool,
  completeTaskTool,
  generateSubagentPromptTool,
  exportPlanAsMarkdownTool,
  getPlanStatusTool,
  listPlansTool,
  markPlanReadyTool,
  // v0.6 Systematic Debugging
  startDebugSessionTool,
  logInvestigationTool,
  addEvidenceTool,
  completePhase1Tool,
  logPatternsTool,
  completePhase2Tool,
  formHypothesisTool,
  testHypothesisTool,
  implementFixTool,
  verifyFixTool,
  getDebugSessionTool,
  listDebugSessionsTool,
  checkRedFlagsTool,
} from "./tools.js";

const server = new McpServer({
  name: "mcp-swarm",
  version: "0.6.0",
});

server.registerTool(...agentRegisterTool);
server.registerTool(...agentWhoamiTool);
server.registerTool(...companionStatusLocalTool);
server.registerTool(...companionStopLocalTool);
server.registerTool(...companionPauseLocalTool);
server.registerTool(...companionResumeLocalTool);
server.registerTool(...broadcastChatTool);
server.registerTool(...swarmStopStatusTool);
server.registerTool(...swarmStopTool);
server.registerTool(...swarmResumeTool);
server.registerTool(...syncWithBaseBranchTool);
server.registerTool(...taskCreateTool);
server.registerTool(...taskListTool);
server.registerTool(...taskLinkTool);
server.registerTool(...taskSetStatusTool);
server.registerTool(...taskAssignTool);
server.registerTool(...taskMarkDoneTool);
server.registerTool(...taskCancelTool);
server.registerTool(...updateTeamDashboardTool);
server.registerTool(...worktreeCreateTool);
server.registerTool(...worktreeListTool);
server.registerTool(...worktreeRemoveTool);
// New tools
server.registerTool(...scanSystemMcpsTool);
server.registerTool(...authorizeMcpsForSwarmTool);
server.registerTool(...getPolicyTool);
server.registerTool(...fileReserveTool);
server.registerTool(...fileReleaseTool);
server.registerTool(...listFileLocksTool);
server.registerTool(...announceTaskForBiddingTool);
server.registerTool(...bidForTaskTool);
server.registerTool(...pollSwarmEventsTool);
server.registerTool(...createGithubPrTool);
server.registerTool(...checkMainHealthTool);
server.registerTool(...signalDependencyChangeTool);
server.registerTool(...syncDependenciesTool);
server.registerTool(...requestCrossAgentReviewTool);
server.registerTool(...respondToReviewTool);
server.registerTool(...listPendingReviewsTool);
server.registerTool(...shareScreenshotTool);
server.registerTool(...listScreenshotsTool);
// v0.3 tools
server.registerTool(...decomposeTaskTool);
server.registerTool(...getDecompositionTool);
server.registerTool(...startVotingTool);
server.registerTool(...castVoteTool);
server.registerTool(...listOpenVotingsTool);
server.registerTool(...autoDeleteMergedBranchTool);
server.registerTool(...cleanupAllMergedBranchesTool);
server.registerTool(...logSwarmThoughtTool);
server.registerTool(...getRecentThoughtsTool);
server.registerTool(...patrolModeTool);
server.registerTool(...reportCiAlertTool);
server.registerTool(...getImmuneStatusTool);
server.registerTool(...runLocalTestsTool);
server.registerTool(...forecastFileTouchesTool);
server.registerTool(...checkFileConflictsTool);
server.registerTool(...requestPlatformCheckTool);
server.registerTool(...respondToPlatformCheckTool);
server.registerTool(...getPendingPlatformChecksTool);
// v0.4 orchestrator tools
server.registerTool(...saveBriefingTool);
server.registerTool(...loadBriefingTool);
server.registerTool(...updateSwarmPulseTool);
server.registerTool(...getSwarmPulseTool);
server.registerTool(...archiveFindingTool);
server.registerTool(...searchKnowledgeTool);
server.registerTool(...triggerUrgentPreemptionTool);
server.registerTool(...getActiveUrgentTool);
server.registerTool(...createSnapshotTool);
server.registerTool(...triggerRollbackTool);
server.registerTool(...requestCollectiveAdviceTool);
server.registerTool(...provideAdviceTool);
server.registerTool(...autoGenerateDocsTool);
server.registerTool(...trackExpertiseTool);
server.registerTool(...suggestAgentForTaskTool);
server.registerTool(...predictConflictsTool);
// v0.4.1 Enhanced features
server.registerTool(...generateTaskDocsTool);
server.registerTool(...listDocsTool);
server.registerTool(...getDocTool);
server.registerTool(...recordAgentEditTool);
server.registerTool(...suggestAgentAdvancedTool);
server.registerTool(...getTopExpertsTool);
server.registerTool(...listAgentExpertiseTool);
server.registerTool(...analyzeConflictHistoryTool);
server.registerTool(...getConflictHotspotsTool);
server.registerTool(...checkFileSafetyTool);
server.registerTool(...recordConflictEventTool);

// v0.4.2 Timeline
server.registerTool(...generateTimelineTool);
server.registerTool(...getTimelineVisualizationTool);

// v0.5 Agent Health Monitor
server.registerTool(...checkAgentHealthTool);
server.registerTool(...getDeadAgentsTool);
server.registerTool(...forceReassignTaskTool);
server.registerTool(...getSwarmHealthSummaryTool);

// v0.5 Session Recording
server.registerTool(...startSessionRecordingTool);
server.registerTool(...logSessionActionTool);
server.registerTool(...stopSessionRecordingTool);
server.registerTool(...listSessionRecordingsTool);
server.registerTool(...replaySessionTool);

// v0.5 Quality Gate
server.registerTool(...runQualityGateTool);
server.registerTool(...getQualityReportTool);
server.registerTool(...setQualityThresholdTool);
server.registerTool(...checkPrReadyTool);

// v0.5 Cost Tracker
server.registerTool(...logApiUsageTool);
server.registerTool(...getAgentCostsTool);
server.registerTool(...getProjectCostsTool);
server.registerTool(...setBudgetLimitTool);
server.registerTool(...checkBudgetRemainingTool);

// v0.5 Context Compressor
server.registerTool(...estimateContextSizeTool);
server.registerTool(...compressBriefingTool);
server.registerTool(...compressMultipleBriefingsTool);
server.registerTool(...getCompressionStatsTool);

// v0.5 Regression Detector
server.registerTool(...saveBaselineTool);
server.registerTool(...checkRegressionTool);
server.registerTool(...listRegressionsTool);
server.registerTool(...resolveRegressionTool);
server.registerTool(...listBaselinesTool);

// v0.6 Brainstorming (superpowers-inspired)
server.registerTool(...startBrainstormTool);
server.registerTool(...askBrainstormQuestionTool);
server.registerTool(...answerBrainstormQuestionTool);
server.registerTool(...proposeApproachesTool);
server.registerTool(...presentDesignSectionTool);
server.registerTool(...validateDesignSectionTool);
server.registerTool(...saveDesignDocumentTool);
server.registerTool(...getBrainstormSessionTool);
server.registerTool(...listBrainstormSessionsTool);

// v0.6 Writing Plans (TDD methodology)
server.registerTool(...createImplementationPlanTool);
server.registerTool(...addPlanTaskTool);
server.registerTool(...getNextTaskTool);
server.registerTool(...startPlanTaskTool);
server.registerTool(...completeStepTool);
server.registerTool(...completeTaskTool);
server.registerTool(...generateSubagentPromptTool);
server.registerTool(...exportPlanAsMarkdownTool);
server.registerTool(...getPlanStatusTool);
server.registerTool(...listPlansTool);
server.registerTool(...markPlanReadyTool);

// v0.6 Systematic Debugging (4-phase methodology)
server.registerTool(...startDebugSessionTool);
server.registerTool(...logInvestigationTool);
server.registerTool(...addEvidenceTool);
server.registerTool(...completePhase1Tool);
server.registerTool(...logPatternsTool);
server.registerTool(...completePhase2Tool);
server.registerTool(...formHypothesisTool);
server.registerTool(...testHypothesisTool);
server.registerTool(...implementFixTool);
server.registerTool(...verifyFixTool);
server.registerTool(...getDebugSessionTool);
server.registerTool(...listDebugSessionsTool);
server.registerTool(...checkRedFlagsTool);

server.registerTool(
  "health_check",
  {
    title: "Health Check",
    description: "Returns basic server status",
    inputSchema: z.object({}).strict(),
    outputSchema: z
      .object({
        ok: z.boolean(),
        name: z.string(),
        version: z.string(),
      })
      .strict(),
  },
  async () => {
    const output = { ok: true, name: "mcp-swarm", version: "0.1.0" };
    return {
      content: [{ type: "text" as const, text: JSON.stringify(output) }],
      structuredContent: output,
    };
  }
);

async function main() {
  const transport = new StdioServerTransport();
  await server.connect(transport);
}

main().catch(err => {
  // eslint-disable-next-line no-console
  console.error(err);
  process.exit(1);
});
